web:
    container_name: pynginx
    image: doberbeatz/nginxgunicorn
    ports:
    - "80:80"
    volumes:
    - .:/home/www/microblog
    restart: always
    env_file: .env
    command: /home/www/microblog/run.sh
