web:
    container_name: pynginx
    image: doberbeatz/nginxgunicorn
    ports:
    - "8080:80"
    volumes:
    - .:/home/www/microblog
    restart: always
    command: bash -c "service nginx start && cd /home/www/microblog && source ./flask/bin/activate && ./run.py"
